version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: notclal-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-notclal_insurance}
      POSTGRES_USER: ${POSTGRES_USER:-notclal_admin}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
      - ./database/backups:/backups
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-notclal_admin} -d ${POSTGRES_DB:-notclal_insurance}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notclal-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: notclal-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@notclal.com}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    secrets:
      - pgadmin_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - notclal-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  notclal-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt